# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java21
# instance_class: F2 - this is standard environment specific according to GPT
# runtime: java
env: flex

automatic_scaling:
  max_num_instances: 1
  # min_num_instances: 1 # at least 1 instance running, so data in H2 database will not be throw away when no user acess?
